//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAndPassword2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class megaList
    {
        public int restaurant_id { get; set; }

        [Display(Name = "Name")]
        public string restaurant_name { get; set; }
        [Display(Name = "Location")]
        public string restaurant_location { get; set; }
        public Nullable<int> ranking { get; set; }
        [Display(Name = "Service")]
        public int service { get; set; }
        [Display(Name = "Service Comment")]
        public string service_comment { get; set; }
        [Display(Name = "Value")]
        public int value { get; set; }
        [Display(Name = "Value Comment")]
        public string value_comment { get; set; }
        [Display(Name = "Ambience")]
        public int ambience { get; set; }
        [Display(Name = "Ambience Comment")]
        public string ambience_comment { get; set; }
        [Display(Name = "Menu")]
        public int menu { get; set; }
        [Display(Name = "Menu Comment")]
        public string menu_comment { get; set; }
        [Display(Name = "Eco-Friendly")]
        public int eco_friendly { get; set; }
        [Display(Name = "Eco-Friendly Comment")]
        public string eco_friendly_comment { get; set; }
        [Display(Name = "Would go again")]
        public Nullable<bool> would_go_again { get; set; }
        [Display(Name = "I would be encouraged back if...")]
        public string tempt_me_back { get; set; }
    }
}
