//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAndPassword2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class megaList
    {
        public int restaurant_id { get; set; }
        public string restaurant_name { get; set; }
        public string restaurant_location { get; set; }
        public Nullable<int> ranking { get; set; }
        public int service { get; set; }
        public string service_comment { get; set; }
        public int value { get; set; }
        public string value_comment { get; set; }
        public int ambience { get; set; }
        public string ambience_comment { get; set; }
        public int menu { get; set; }
        public string menu_comment { get; set; }
        public int eco_friendly { get; set; }
        public string eco_friendly_comment { get; set; }
        public Nullable<bool> would_go_again { get; set; }
        public string tempt_me_back { get; set; }
    }
}
